/**
 * Every bit in Makera's Fusion 360 tool library, with the presets Makera ships
 * for each material. One table for anything that needs to know a Makera bit:
 * materials.ts takes its facing bits from here.
 *
 * makera-bits.json is generated by scripts/makera-library.ts from Makera's
 * CarveraProfiles repository; regenerate it rather than edit it. Presets use
 * catalogue.ts's material columns, which are the same eight Makera uses.
 */

import type { CatMaterial, Kind } from "./catalogue.ts";
import data from "./makera-bits.json";

export type LibraryKind = Kind | "thread";

export interface Preset {
  readonly rpm: number;
  /** mm/min, lateral. Absent for drills. */
  readonly feed?: number;
  /** mm/min, Z. */
  readonly plunge?: number;
  /** Depth of cut per pass, mm. Absent for drills. */
  readonly doc?: number;
}

export interface LibraryBit {
  readonly id: string;
  /** The library's own name for it. */
  readonly name: string;
  readonly kind: LibraryKind;
  /** Metal series or not; flat ends, ball ends and engraving bits only. */
  readonly metal?: boolean;
  /** Cutting diameter; for a V-bit or chamfer, the tip. */
  readonly diameter: number;
  /** Shank diameter: the collet it needs. */
  readonly shank: number;
  /** Flute length, mm. */
  readonly flute: number;
  readonly flutes: number;
  /** Included angle, V-bits and chamfer. */
  readonly angle?: number;
  /** Makera's product page. */
  readonly url?: string;
  readonly presets: Partial<Record<CatMaterial, Preset>>;
}

/** The CarveraProfiles commit the library was generated from. */
export const LIBRARY_SOURCE: string = data.source;

export const LIBRARY = data.bits as readonly LibraryBit[];

export const libraryBit = (id: string) => LIBRARY.find((b) => b.id === id);

/**
 * The size in a bit's name, `6*30mm` -> 6 and 30. The name, not the geometry,
 * tells bits apart: Fusion gives two 6mm Metal bits the same 25mm flute length.
 */
export function nominalSize(b: LibraryBit): { diameter: number; flute: number } {
  const m = /(\d+(?:\.\d+)?)\*(\d+(?:\.\d+)?)/.exec(b.name);
  return m ? { diameter: Number(m[1]), flute: Number(m[2]) } : { diameter: b.diameter, flute: b.flute };
}
